name: kaspi_copy
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.4.1
  redux: ^5.0.0
  provider: ^6.1.2
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  meta: ^1.15.0

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true
  assets: 
      - assets/
      - assets/icons/
      - assets/icons_from_original/
      - assets/main_history_images/
      - assets/online_market/



  fonts:
    - family: Roboto
      fonts:
        - asset: assets/roboto_font/Roboto-Black.ttf
        - asset: assets/roboto_font/Roboto-Bold.ttf
        - asset: assets/roboto_font/Roboto-Light.ttf
        - asset: assets/roboto_font/Roboto-Regular.ttf

